AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: items-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold

  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/get-items/
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: items-table
      Events:
        GetItemsApi:
          Type: Api
          Properties:
            Path: /items
            Method: GET

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/create-item/
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: items-table
      Events:
        CreateItemApi:
          Type: Api
          Properties:
            Path: /items
            Method: POST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"