name: Deploy Serverless API

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-2

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset